//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 管理系统
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ManagementEntities : DbContext
    {
#if LYPC
        public ManagementEntities()
    : base("name=LYPCManagementEntities")
        {
        }
#else
        public ManagementEntities()
    : base("name=ManagementEntities")
        {
        }
#endif


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<TiDan> TiDans { get; set; }
    }
}
