//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiDan
    {
        public string FHFS { get; set; }
        public string CPH { get; set; }
        public string LSH { get; set; }
        public string QFH { get; set; }
        public string TDH { get; set; }
        public int YFL { get; set; }
        public Nullable<int> SFL { get; set; }
        public string CZY { get; set; }
        public string HTH { get; set; }
        public string CPGH { get; set; }
        public string PCH { get; set; }
        public string HWH { get; set; }
        public Nullable<int> PZ { get; set; }
        public Nullable<int> MZ { get; set; }
        public Nullable<int> JZ { get; set; }
        public string WLMC { get; set; }
        public string HC { get; set; }
        public string FHDW { get; set; }
        public string SHDW { get; set; }
        public string LX { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string BZ { get; set; }
    }
}
